[project]
name = 'stacks-bodega-cat'
description = ''
authors = []
telemetry = false
cache_dir = '.\.cache'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'
[contracts.bodega-cat]
path = 'contracts/bodega-cat.clar'
clarity_version = 1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
